# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - strillit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://strilliapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8e7194f81dd9401d99f067dfb496969b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5d41e23393e043a690f65e5b6dac36cf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: strilliapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8e7194f81dd9401d99f067dfb496969b }}/nuevaapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'strillit'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9369ca287c5749318100be38667bf85f }}
        images: 'strilliapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8e7194f81dd9401d99f067dfb496969b }}/nuevaapp:${{ github.sha }}'